name: Nations
main: io.github.mosestroyer.nations.Nations
version: 0.1

commands:
   growcrops:
      description: Grow the wheat around you
      
   digtunnel:
      description: Digs a tunnel in front of you
      
   heal:
      description: Heals your Player