name: Nations
main: io.github.mosestroyer.nations.Nations
version: 0.1

commands:
    createNationsBoard:
        description: Creates a board to display nations and other information
    createPedestal:
        description: Creates a pedestal for a designated nation
    createNation:
        description: Allows an admin to setup a new nation
    showNations:
        description: Shows the list of all created nations
    removeNation:
        description: Removes a nation from the nationlist
    joinNation:
        description: Joins a specified nation
    leaveNation:
        description: Leave your nation
    growcrops:
        description: Grow the wheat around you
    digtunnel:
        description: Digs a tunnel in front of you
    heal:
         description: Heals your Player
    fireball:
         description: Shoots a fireball!
    arrowstorm:
         description: shoots a stream of arrows
    teleportspawn:
         description: teleports you home
    killself:
         description: kills you
    givespellbook:
         description: gives you a spellbook
         
permissions:
    nations.*:
        description: Access to all nations commands
        children:
            nations.admin: true
            nations.monarch: true
            nations.citizen: true
            nations.commonder: true
    nations.admin:
        description: The abilities for the server admins
        default: false
    nations.monarch:
        description: The abilities for the rulers of a nation
        default: false
    nations.citizen:
        description: The abilities for the citizens of a nation
        default: false
    nations.commoner:
        description: The abilities for a nation-less commoner
        default: true