name: Nations
main: io.github.mosestroyer.nations.Nations
version: 1.0
depend: [WorldGuard]

commands:
    createNationsBoard:
        permission: nations.admin
        description: Creates a board to display nations and other information
    createPedestal:
        permission: nations.admin
        description: Creates a pedestal for a designated nation
    removePedestal:
        permission: nations.admin
        description: Removes a pedestal for a designated nation
    createNation:
        permission: nations.admin
        description: Allows an admin to setup a new nation
    showNations:
        description: Shows the list of all created nations
    removeNation:
        permission: nations.admin
        description: Removes a nation from the nationlist
    joinNation:
        description: Joins a specified nation
    leaveNation:
        description: Leave your nation
    setClass:
        permission: nations.admin
        description: Sets the player's class
    givespellbook:
        permission: nations.admin
        description: gives you a spellbook
         
permissions:
    nations.*:
        description: Access to all nations commands
        children:
            nations.admin: true
            nations.monarch: true
            nations.citizen: true
            nations.commonder: true
        default: op
    nations.admin:
        description: The abilities for the server admins
        default: false
    nations.monarch:
        description: The abilities for the rulers of a nation
        default: false
    nations.citizen:
        description: The abilities for the citizens of a nation
        default: false
    nations.commoner:
        description: The abilities for a nation-less commoner
        default: true